email_to = ENV['EMAIL_TO']
email_day_of_week = ENV['EMAIL_DAY_OF_WEEK']
if email_to and (email_day_of_week == nil or email_day_of_week == Time::now.wday.to_s)
  Mail.defaults do
    delivery_method :smtp, {
      :address => 'smtp.sendgrid.net',
      :port => '587',
      :domain => 'heroku.com',
      :user_name => ENV['SENDGRID_USERNAME'],
      :password => ENV['SENDGRID_PASSWORD'],
      :authentication => :plain,
      :enable_starttls_auto => true
    }
  end

  puts "Emailing report to #{email_to}"
  mail = Mail.new do
    from     ENV['EMAIL_FROM']
    to       ENV['EMAIL_TO']
    subject  ENV['EMAIL_SUBJECT'] % timestamp
    body     "Automatically generated by heroku-cloud-stats"
    add_file :filename => 'reserved instances %s.csv' % timestamp, :content => reservations_csv
    add_file :filename => 'running instances %s.csv' % timestamp, :content => instances_csv
  end
  mail.deliver!
else
  puts reservations_csv
  puts
  puts instances_csv
end

